---
- name: ngingx repository
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
  tags: nginx

- name: Install nginx
  yum: name={{item}} state=installed
  with_items:
    - nginx
  tags: nginx

- name: nginx kibana.conf
  template: >
     src=nginx_kibana.conf.j2
     dest=/etc/nginx/conf.d/nginx_kibana.conf
     owner=root
     group=root
     mode=0644
  tags: nginx
  notify: restart nginx
